### ISSUE TITLE
ValueError: Non-consecutive added token '<unk>' found. Should have index 32000 but has index 0 in saved vocabulary.

### ISSUE THREAD

**Issue by SaloniHenecha24** [leliuga/cohere-configurations#23]
### Package architecture

- [ ] linux/amd64 (x86_64)

### Our host architecture

Open-Orca/Mistral-7B-OpenOrca

### Describe the bug

I am using same model card as on Huggingface, It has been working since last week, today giving error : 
" ValueError: Non-consecutive added token '<unk>' found. Should have index 32000 but has index 0 in saved vocabulary. "

### Steps To Reproduce

# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("Open-Orca/Mistral-7B-OpenOrca")
model = AutoModelForCausalLM.from_pretrained("Open-Orca/Mistral-7B-OpenOrca")

### Expected behavior

Model should be loaded.

### Actual behavior

tokenizer_config.json: 100%
 1.58k/1.58k [00:00<00:00, 207kB/s]
tokenizer.model: 100%
 493k/493k [00:00<00:00, 41.7MB/s]
added_tokens.json: 100%
 90.0/90.0 [00:00<00:00, 16.1kB/s]
special_tokens_map.json: 100%
 174/174 [00:00<00:00, 32.4kB/s]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[7], line 7
      4 base_model =  "Open-Orca/Mistral-7B-OpenOrca"
      5 base_model = "Open-Orca/Mistral-7B-SlimOrca"
----> 7 tokenizer = AutoTokenizer.from_pretrained(base_model)
      8 model = AutoModelForCausalLM.from_pretrained(base_model)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py:702, in AutoTokenizer.from_pretrained(cls, pretrained_model_name_or_path, *inputs, **kwargs)
    698     if tokenizer_class is None:
    699         raise ValueError(
    700             f"Tokenizer class {tokenizer_class_candidate} does not exist or is not currently imported."
    701         )
--> 702     return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
    704 # Otherwise we have to be creative.
    705 # if model is an encoder decoder, the encoder tokenizer class is used by default
    706 if isinstance(config, EncoderDecoderConfig):

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1841, in PreTrainedTokenizerBase.from_pretrained(cls, pretrained_model_name_or_path, cache_dir, force_download, local_files_only, token, revision, *init_inputs, **kwargs)
   1838     else:
   1839         logger.info(f"loading file {file_path} from cache at {resolved_vocab_files[file_id]}")
-> 1841 return cls._from_pretrained(
   1842     resolved_vocab_files,
   1843     pretrained_model_name_or_path,
   1844     init_configuration,
   1845     *init_inputs,
   1846     use_auth_token=token,
   1847     cache_dir=cache_dir,
   1848     local_files_only=local_files_only,
   1849     _commit_hash=commit_hash,
   1850     _is_local=is_local,
   1851     **kwargs,
   1852 )

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1873, in PreTrainedTokenizerBase._from_pretrained(cls, resolved_vocab_files, pretrained_model_name_or_path, init_configuration, use_auth_token, cache_dir, local_files_only, _commit_hash, _is_local, *init_inputs, **kwargs)
   1871 has_tokenizer_file = resolved_vocab_files.get("tokenizer_file", None) is not None
   1872 if (from_slow or not has_tokenizer_file) and cls.slow_tokenizer_class is not None:
-> 1873     slow_tokenizer = (cls.slow_tokenizer_class)._from_pretrained(
   1874         copy.deepcopy(resolved_vocab_files),
   1875         pretrained_model_name_or_path,
   1876         copy.deepcopy(init_configuration),
   1877         *init_inputs,
   1878         use_auth_token=use_auth_token,
   1879         cache_dir=cache_dir,
   1880         local_files_only=local_files_only,
   1881         _commit_hash=_commit_hash,
   1882         **(copy.deepcopy(kwargs)),
   1883     )
   1884 else:
   1885     slow_tokenizer = None

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:2060, in PreTrainedTokenizerBase._from_pretrained(cls, resolved_vocab_files, pretrained_model_name_or_path, init_configuration, use_auth_token, cache_dir, local_files_only, _commit_hash, _is_local, *init_inputs, **kwargs)
   2053     raise ValueError(
   2054         f"Wrong index found for {token}: should be {tokenizer.convert_tokens_to_ids(token)} but found "
   2055         f"{index}."
   2056     )
   2057 elif not has_tokenizer_file and index != current_index:
   2058     # Tokenizer slow: added token cannot already be in the vocabulary so its index needs to be the
   2059     # current length of the tokenizer.
-> 2060     raise ValueError(
   2061         f"Non-consecutive added token '{token}' found. "
   2062         f"Should have index {current_index} but has index {index} in saved vocabulary."
   2063     )
   2065 is_special = bool(token in special_tokens)
   2066 if is_last_special is None or is_last_special == is_special:

ValueError: Non-consecutive added token '<unk>' found. Should have index 32000 but has index 0 in saved vocabulary.

### Code of Conduct

- [X] I agree to follow this repository Code of Conduct

**Comment by evaldas-leliuga** [comment]
@SaloniHenecha24 cohere-configurations is for GGUF registry not for Transformers.
